eureka:
  client:
    serviceUrl:
defaultZone: http://admin:admin123@10.0.0.2:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: say-hello-service
  zipkin:
    base-url: http://10.0.0.2:9411
